[package]
name = "gr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#Local crate: gr-tui
gr-tui = { path = "src/gr-tui" }
gr-git = { path = "src/gr-git" }
